baseURL = 'https://blog.josehernandez.dev/'
languageCode = 'en-us'
title = 'Jose Hernandez'
theme = 'jah'

[params]
  author        = 'Jose Hernandez'
  description   = 'Engineering. Architecture. Craft.'
  tagline       = 'Engineering done right. Written down.'
  githubHandle  = ''
  twitterHandle = ''

[taxonomies]
  tag      = 'tags'
  category = 'categories'

[pagination]
  pagerSize = 9

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style     = 'dracula'
    noClasses = false
[caches]
  [caches.images]
    dir = ':cacheDir/images'